apiVersion: v1
kind: Namespace
metadata:
  labels:
    tier: $TIER1
  name: $TIER1
spec:

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $TIER1
  name: $TIER1
  namespace: $TIER1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $TIER1
  template:
    metadata:
      labels:
        app: $TIER1
        tier: $TIER1
    spec:
      containers:
      - image: nginx
        name: nginx

---



apiVersion: v1
kind: Namespace
metadata:
  labels:
    tier: $TIER2
  name: $TIER2
spec:

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $TIER2
  name: $TIER2
  namespace: $TIER2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $TIER2
  template:
    metadata:
      labels:
        app: $TIER2
        tier: $TIER2
    spec:
      containers:
      - image: nginx
        name: nginx

---



apiVersion: v1
kind: Namespace
metadata:
  labels:
  name: $TIER3
spec:

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $TIER3
  name: $TIER3
  namespace: $TIER3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $TIER3
  template:
    metadata:
      labels:
        app: $TIER3
        tier: $TIER3
    spec:
      containers:
      - image: nginx
        name: nginx

---



